### ISSUE TITLE
Runtime error: LoadError: MethodError: no method matching logdensity(::AddTypos, ::String3, ::String3)

### ISSUE THREAD

**Issue by sufengniu** [probcomp/PClean#23]
Hello, I am new to both PClean and Julia, when I tried to run the PClean experiments (julia --project=. experiments/hospital/run.jl), I got the following errors:

```
ERROR: LoadError: MethodError: no method matching logdensity(::AddTypos, ::String3, ::String3)
Closest candidates are:
  logdensity(::FormatName, ::Any, ::Any) at ~/lab/PClean/src/distributions/format_name.jl:33
  logdensity(::FormatName, ::Any, ::Any, ::Any, ::Any) at ~/lab/PClean/src/distributions/format_name.jl:14
  logdensity(::ExpandOnShortVersion, ::Any, ::Any, ::Any) at ~/lab/PClean/src/distributions/expand_on_short_version.jl:30
  ...
Stacktrace:
 [1] var"##663"(state#321::PClean.ProposalRowState)
   @ PClean ~/lab/PClean/src/inference/proposal_compiler.jl:101
 [2] #invokelatest#2
   @ ./essentials.jl:716 [inlined]
 [3] invokelatest
   @ ./essentials.jl:714 [inlined]
 [4] make_block_proposal!(state::PClean.ProposalRowState, block_index::Int64, config::PClean.InferenceConfig)
   @ PClean ~/lab/PClean/src/inference/block_proposal.jl:175
 [5] extend_particle!(particle::PClean.SMCParticle, config::PClean.InferenceConfig)
   @ PClean ~/lab/PClean/src/inference/row_inference.jl:70
 [6] run_smc!(trace::PClean.PCleanTrace, class::Symbol, key::Int64, config::PClean.InferenceConfig)
   @ PClean ~/lab/PClean/src/inference/row_inference.jl:146
 [7] initialize_trace(observations::Vector{ObservedDataset}, config::PClean.InferenceConfig)
   @ PClean ~/lab/PClean/src/inference/inference.jl:37
 [8] macro expansion
   @ ~/lab/PClean/experiments/hospital/run.jl:79 [inlined]
 [9] top-level scope
   @ ./timing.jl:220
in expression starting at /Users/sniu/lab/PClean/experiments/hospital/run.jl:78
```
my Julia version is 1.7.2, I searched online and found one similar issues (https://discourse.julialang.org/t/error-loaderror-methoderror-no-method-matching-setindex-shape-check-int64-int64-int64/18249) mentioned about new Julia need to do the broadcasting, but from error messages, I haven't figured out where to adjust it or maybe I go to the wrong direction. Any insights are appreciated. Thank you!

Sufeng

**Comment by alex-lew** [comment]
Hi, thanks for trying out PClean, and for reporting this bug!

It looks like the `CSV` package was recently updated to use a new String type, that PClean is not yet compatible with. For now, I've updated the `Project.toml` file to fix the CSV package version at 0.8.5. Could you try again? (You may need to run `Pkg.resolve()` after pulling the repo, or just start with a fresh version of the repo.)
