### ISSUE TITLE
How to handle when a column is an array of struct

### ISSUE THREAD

**Issue by sufengniu** [probcomp/PClean#24]
Hello,

I wonder if anyone has insights that when a table column is an array of struct, which is very common in real world database, for example, consider someone's profile has following schema:

```
  {
    "type": "array",
    "items": [
      {
        "type": "record",
        "name": "schools",
        "fields": [
          {
            "name": "school_name",
            "type": [
              "string"
            ]
          },
          {
            "name": "degree",
            "type": [
              "string"
            ]
          }
        ]
      },
    ]
  },
```
one example is:
```
    Name        |            schools                                     
    A           | [[MIT, Phd],                [MIT, master],            [MIT, bachrlo]]
    B           | [[Boston U, master], [Boston U, bachelor]]
    C           | [[CMU, bachelor]]
```

the most naive way I can think is break each school array as single element, like followings:
```
    Name        |            schools                                     
    A           |       [MIT, Phd]                           
    A           |       [MIT, master] 
    A           |       [MIT, bachrlo]

```
but I think this method would loss the relational information for one person, for example, if I know A study master at MIT, then it is possible that previous degree at MIT is bachelor instead of a typo (bachrlo)

So my question is:
1) how can we properly handle when the column is an array of a data structure
2) if columns have hierarchy structure, just confirm if I did correct or not: I should simply build this hierarchy structure into the PClean program (like a bayesian network ), and then just align them with hierarchy column names, am I correct here?

Thank you!

**Comment by alex-lew** [comment]
> if columns have hierarchy structure, just confirm if I did correct or not: I should simply build this hierarchy structure into the PClean program (like a bayesian network ), and then just align them with hierarchy column names, am I correct here?

Sorry, I missed this part of the question :)

Broadly, there are two ways to handle structured attributes. As an example, consider a dataset matching people with workplaces, where each record is of the form (person, company). "Person" is a structured object with attributes first name, last name, age, and company is a structured object with attributes company name, company address. We could model this by:

1. **Flattening the structure.** We could implement a "Record" class that has separate attributes for first_name, last_name, age, company_name, and company_address.

2. **Model with a new class.** We could implement "Person" and "Company" classes, each with their own attributes, and then model a "Record" as pointing to a Person and a Company.

The first choice is suitable if you expect any given person or company to only appear once in the data.

The second choice is suitable if you expect the same people and companies to recur throughout the dataset—this way PClean can learn a latent database of people and companies, and figure out which rows of your data refer to which people and to which companies.

**Comment by sufengniu** [comment]
very thorough answers. Thank you very much!
